### ISSUE TITLE
Are you planning any compataibility with .net core?

### ISSUE THREAD

**Issue by maulik-modi** [tayyabnasir22/Kendo-JQuery-Grid-Server-Filtering-Sorting-Aggregate-Mapping#2]
Are you planning any compataibility with .net core?

**Comment by tayyabnasir22** [comment]
Not working on any such comparability for now. Might plan to work on it in the future.

**Comment by tayyabnasir22** [comment]
Will keep the issue open to keep it as a reminder to provide the required .net core comparability.

**Comment by tayyabnasir22** [comment]
@maulik-modi Added support for .NET Core and .NET Standard.
