### ISSUE TITLE
Question: How do I pass DatasourceRequest from javascript to get this expression

### ISSUE THREAD

**Issue by maulik-modi** [tayyabnasir22/Kendo-JQuery-Grid-Server-Filtering-Sorting-Aggregate-Mapping#3]
@tayyabnasir22 , Excellent package.

How do I pass DatasourceRequest from javascript to get this expression. Note that I am using Kendo angular
(( projectNumber >= 123) and ( projectName like 'a%') and (( projectType = 'Combo') or ( projectType = '504')))

**Comment by tayyabnasir22** [comment]
@maulik-modi the project was designed to facilitate **Kendo jQuery Grid** where the filters are passed in the following format:
```
take: 20
skip: 0
page: 1
pageSize: 20
filter[logic]: or
filter[filters][0][field]: projectName
filter[filters][0][operator]: startswith
filter[filters][0][value]: s
filter[filters][1][field]: projectName
filter[filters][1][operator]: startswith
filter[filters][1][value]: p
aggregate[0][field]: projectName
aggregate[0][aggregate]: count
aggregate[1][field]: projectAmount
aggregate[1][aggregate]: sum
aggregate[2][field]: projectFee
aggregate[2][aggregate]: sum
```

I believe if the Kendo Grid for Angular uses the same format to pass selected filters then surely the current will work for Angular Grid as well. However, if that's not the case then it will fail.

**Comment by maulik-modi** [comment]
@tayyabnasir22 , I checked https://demos.telerik.com/kendo-ui/grid/remote-data-binding and inspected querystring, URL and querystring are generated in below format. 

Does this package parse querystring?

`https://demos.telerik.com/kendo-ui/service/Northwind.svc/Orders?$callback=jQuery112405675577947570511_1618548285786&%24inlinecount=allpages&%24format=json&%24top=20&%24filter=((startswith(ShipName%2C%27v%27)+or+startswith(ShipName%2C%27h%27))+and+(startswith(ShipCity%2C%27r%27)+or+startswith(ShipCity%2C%27l%27))`

`'$filter: ((startswith(ShipName,'v') or startswith(ShipName,'h')) and (startswith(ShipCity,'r') or startswith(ShipCity,'l')))'`

**Comment by tayyabnasir22** [comment]
@maulik-modi yes it does, relying on ASP.NET MVC based mappings for given query string to DataSourceRequest model object.

**Comment by maulik-modi** [comment]
@tayyabnasir22 , Is the generated expression - SQL Injection safe?

**Comment by tayyabnasir22** [comment]
@maulik-modi it just generates a string, which can be used to create a dynamic where clause, and not the query itself. As far as SQL injection is concerned that is something that has to be dealt with when you are actually creating your query that will utilize this string (a number of techniques may exists based on which datasource you are using).

**Comment by maulik-modi** [comment]
@tayyabnasir22 , What is the best way to declare GET Action method to receive DataSourceRequest in model?
@tayyabnasir22 , I checked https://github.com/telerik/kendo-ui-demos-service/blob/master/graphql/graphql-aspnet-core/graphql-aspnet-core/Controllers/CustomersController.cs and I am seeing Action method has DatasourceRequestModelBinder. Is it possible to include that class in your package for seamless integration?

**Comment by maulik-modi** [comment]
@tayyabnasir22 
This is officially mentioned by Telerik - using DataSourceRequest as a model in web API will not work out of the box and it does require Custom model binder, refer https://www.telerik.com/blogs/the-facts-on-using-kendo-ui-with-asp-net-webapi, section - MVC vs WebAPI Parameter Binding.

Looks like code sample is provided here - https://www.telerik.com/support/code-library/binding-to-a-web-apicontroller-6cdc432b8326

**Comment by tayyabnasir22** [comment]
@maulik-modi if you look into the code for Kendo-FASM you will find that DataSourceRequest used here is a custom object and has nothing to do with Telerik UI for MVC. As far as Kendo FASM DataSourceRequest  is concerned, it maps perfectly with the data being sent from Kendo jQuery Grid.

**Comment by maulik-modi** [comment]
@tayyabnasir22 , we are looking to integrate angular kendo grid with asp.net core API. It is not binding Filter property of DataSourceRequest. Kendo team is recommending to implement custom model binder. Hence I wanted to know your thoughts on Custom model binder. Once DataSourceRequest is bound correctly in Action, your package helps in generating expression.

**Comment by tayyabnasir22** [comment]
@maulik-modi yes I did some digging of my own and as per team Kendo you have to write a custom binder for Angular Grid as the filters request is not same as that for jQuery. Also if you want you can extend the existing code and introduce your custom binder as well.
